openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"

  /customer:
    get:
      description: "Get All customers"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
          example: 530b93b7-c676-4fe9-a6d4-13ac1b1cacd5
        name:
          type: string
          example: Arthur
        lastName:
          type: string
          example: Dent
        email:
          type: string
          example: test@example.com
      required:
        - id
        - name
        - lastName
        - email
